version: 2.1

jobs:
  compile:
    docker:
      - image: cimg/base:2023.03
    steps:
      - checkout
      - run: echo "xddd"
  validate:
    docker:
      - image: cimg/base:2023.03
    steps:
      - checkout
      - run: echo "xddd"

workflows:
  compile_and_validate:
    jobs:
      - compile
      - validate
